### PR TITLE
changing field_tier from select list to taxonomy

### PR DESCRIPTION
**Pull request by barrettbaffert**
still need to update feature; adjust twig templates and migration

### CODE REVIEW

**Comment by barrettbaffert** [comment]
@noother84 when running migration locally, I'm getting this error in my terminal pretty regularly 

```
 [warning] Missing file with ID . ImageItem.php:327
 [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:264
```

Could it be because `field_profile_photo/target_id` is in single quotes here? 

https://github.com/barrettbaffert/gershon/pull/2/files#diff-a849ea8892a68ab1cd2a7e9a6a513a01R855

I don't know if that's as expected or not

**Comment by noother84** [comment]
The single quotes should be fine, and wouldn't cause that error. That typically only shows up if it can't find a photo for the player. My local instance isn't working right now (and internet was down until now), but I'll do some debugging as to why that is occurring.

**Comment by barrettbaffert** [comment]
Great, thanks! Just one other question for now. I haven't been able to migrate tier values yet. Could it be because I need to change `$return_value`s here from `1` to the taxonomy value or text?

https://github.com/barrettbaffert/gershon/blob/master/web/modules/custom/custom_json_migrate/src/Plugin/migrate/process/FormatTier.php#L74

**Comment by noother84** [comment]
Actually, if the taxonomy terms for tier are what the concatenated values are, you could probably just remove the format_tier plugin altogether from the YML. FormatTier.php maps the concatenated values to their text format, and would be unnecessary for the taxonomy lookup.

**Comment by barrettbaffert** [comment]
@noother84 these combination of updates to `custom_json_migrate_players.yml` and `FormatTier.php`

https://github.com/barrettbaffert/gershon/pull/2/commits/70bd75b865b9fc2ed42900470f7e8d0e1f265125#diff-7fc43915f59d1128c8bcabf8f605aa03

https://github.com/barrettbaffert/gershon/pull/2/commits/70bd75b865b9fc2ed42900470f7e8d0e1f265125#diff-a849ea8892a68ab1cd2a7e9a6a513a01

**Comment by barrettbaffert** [comment]
> @noother84 these combination of updates to `custom_json_migrate_players.yml` and `FormatTier.php`
> 
> [70bd75b#diff-7fc43915f59d1128c8bcabf8f605aa03](https://github.com/barrettbaffert/gershon/commit/70bd75b865b9fc2ed42900470f7e8d0e1f265125#diff-7fc43915f59d1128c8bcabf8f605aa03)
> 
> [70bd75b#diff-a849ea8892a68ab1cd2a7e9a6a513a01](https://github.com/barrettbaffert/gershon/commit/70bd75b865b9fc2ed42900470f7e8d0e1f265125#diff-a849ea8892a68ab1cd2a7e9a6a513a01)

whoops, didn't finish my thought, I guess... If you see anything wrong with those updates, let me know. Thanks!

**Comment by barrettbaffert** [comment]
> when running migration locally, I'm getting this error in my terminal pretty regularly
> 
> ```
>  [warning] Missing file with ID . ImageItem.php:327
>  [warning] array_flip(): Can only flip STRING and INTEGER values! EntityStorageBase.php:264
> ```

this turns out to be a non-issue. I was only running migration on players, so the image migration for newly created players was never run and player migration had nothing to reference. my mistake! no action required there

**Pull request merged**
